= Wayk Den PowerShell Cmdlet

== Compilation

=== Prerequisites

&#x002E;NET Core 2.0 SDK::
https://dotnet.microsoft.com/download

PowerShell Core 6.0::
https://github.com/PowerShell/PowerShell#get-powershell

=== Build Steps

Build cmdlet:

[source, sh]
----
dotnet publish -f netcoreapp2.2 -c Release
----

Launch powershell and import the Wayk Den module:

[source, sh]
----
$ pwsh
PS > Import-Module ./bin/Release/netcoreapp2.2/publish/WaykDen.dll
----

== Configuration

=== Prerequisites

Docker::
https://docs.docker.com/install/

=== Quick Start

Create a new Wayk Den configuration file, using "contoso.net" as realm and "den.contoso.net" as the external url.

[source, sh]
----
PS > New-WaykDenConfig -Realm contoso.net -ExternalUrl https://den.contoso.net
----

Start Wayk Den, and wait for all microservices to start:

[source, sh]
----
PS > Start-WaykDen -Verbose
----

Once started, Wayk Den listens on http://127.0.0.1:4000 by default. We recommend using a reverse tunnel such as https://ngrok.com/[ngrok] or https://www.cloudflare.com/en-ca/products/argo-tunnel/[argo tunnels] from Cloudflare. In this case, a tunnel is used to expose localhost:4000 on the den.contoso.net external url.

You can check that all containers are up and running:

[source, sh]
----
docker ps -f network=den-network
CONTAINER ID        IMAGE                                      COMMAND                  CREATED              STATUS              PORTS                                                    NAMES
f362a70d2937        traefik:1.7                                "/traefik --rest --a…"   About a minute ago   Up About a minute   0.0.0.0:4000->4000/tcp, 80/tcp, 0.0.0.0:8080->8080/tcp   traefik
dad412b09525        devolutions/den-server:1.2.0-stretch-dev   "./waykden --db_url …"   About a minute ago   Up About a minute   443/tcp, 4491/tcp, 10255/tcp                             den-server
217f585beb47        devolutions/den-router:0.5.0-stretch-dev   "./denrouter"            About a minute ago   Up About a minute   4491/tcp, 10254/tcp                                      den-router
d0f1d5ba9f37        devolutions/den-lucid:3.3.3-stretch-dev    "./lucid --show-conf…"   About a minute ago   Up About a minute   4242/tcp                                                 den-lucid
3aa4ac43d6c2        devolutions/picky:3.0.0-stretch-dev        "./picky-server"         About a minute ago   Up About a minute   12345/tcp                                                den-picky
4500c0b920f9        mongo                                      "docker-entrypoint.s…"   About a minute ago   Up About a minute   27017/tcp                                                den-mongo
----

To confirm everything is correctly up and running, you should be able to get a response from the Wayk Den well known configuration endpoint:

[source, sh]
----
curl http://localhost:4000/.well-known/configuration
{"den_router_uri":"https://den.contoso.net/cow","lucid_uri":"https://den.contoso.net/lucid","realm":"contoso.net","wayk_client_id":"zqdvSbCRWdDrj1fQXwzPQbCg"}
----

If you have correctly configured external access, you should be able to get the same response using the external configuration URL (https://den.contoso.net/.well-known/configuration).

Stop Wayk Den, and wait for all microservices to stop:

[source, sh]
----
PS > Stop-WaykDen -Verbose
----

=== User Management
Wayk Den can be configured to use a specific user group through LDAP integration. Two options are supported: Active Directory and JumpCloud. In order to fetch user and group information, a user with read-only LDAP access must first be created.

==== Active Directory
To integrate Active Directory, here is an example of command that has to be run to set parameters

[source, sh]
----
Set-WaykDenConfig -LDAPServerType ActiveDirectory -LDAPUsername ldap-user@contoso.local -LDAPPassword ldap-password -LDAPServerUrl ldap://ldap-server -LDAPUserGroup 'Domain Users'
----

==== JumpCloud
https://jumpcloud.com/[JumpCloud] is a cloud service who help you to centralize user management. You can create users and groups then use the service call "LDAP-as-a-Service" to access those users and groups from WaykDen. You can read more on https://support.jumpcloud.com/customer/en/portal/articles/2439911-using-jumpcloud-s-ldap-as-a-service[how to use JumpCloud's LDAP-as-a-Service].

To integrate Jump Cloud with Wayk Den, here is an example of command that has to be run to set parameters

[source, sh]
----
Set-WaykDenConfig -LDAPServerType JumpCloud -LDAPUsername uid=ldap-user,ou=Users,o=YOUR_ORG_ID,dc=jumpcloud,dc=com -LDAPPassword ldap-password -LDAPServerUrl ldaps://ldap.jumpcloud.com:636 -LDAPBaseDn ou=Users,o=YOUR_ORG_ID,dc=jumpcloud,dc=com -LDAPUserGroup wayk-users
----
