:toc:
:toclevels: 4

= Wayk Den PowerShell Cmdlet

WaykDen-ps is a PowerShell cmdlet for Wayk Den, the centralized server for https://wayk.devolutions.net[Devolutions Wayk Now]. For assistance or feature requests, please use the https://forum.devolutions.net/#WaykNow[Wayk Now forums] or open a ticket on this github project.

== Installation

=== PowerShell Core
On Windows, the regular PowerShell already installed can be used. On macOS and Linux, you need PowerShell Core 6.0:

PowerShell Core 6.0::
https://github.com/PowerShell/PowerShell#get-powershell

To launch a PowerShell Core terminal, use the `pwsh` command.

=== Wayk Den PowerShell module
A powershell module is available to configure and manage the Wayk Den server. It is available on PSGallery or it could be built directly from https://github.com/Devolutions/WaykDen-ps[source code]. We recommand to install the latest version available on PSGallery, but if needed, a section describe how to build it if you need it.

==== Installation from PSGallery

The Wayk Den PowerShell module is https://www.powershellgallery.com/packages/WaykDen[available on PSGallery].

[source,sh]
----
Install-Module -Name WaykDen -AllowPrerelease
Import-Module WaykDen
----

If you encounter issues with the `Install-Module` command, you may have to https://docs.microsoft.com/en-ca/powershell/gallery/installing-psget[install or update PowerShellGet].

You can then list all commands exported from the `WaykDen` module:

[source,sh]
----
Get-Command -Module WaykDen
----

==== Installation from Source

If you have installed the module from PSGallery, this section is not useful for you. You can jump to the next section. 

To build the Cmdlet, you will need the .NET Core 2.2 SDK and the .NET Framework 4.7.2 SDK. The latter is only needed if you want to support PowerShell for Windows.

 .NET Core 2.2 SDK::
https://dotnet.microsoft.com/download

 .NET Framework 4.7.2 SDK::
https://dotnet.microsoft.com/download/dotnet-framework/net472

From PowerShell, run the build.ps1 script, and then load the resulting PowerShell module:

[source,sh]
----
.\build.ps1
Import-Module "./WaykDen" -Force
----

=== Docker Installation

Wayk Den is composed of multiple microservices running inside Docker containers. The PowerShell cmdlet simplifies the usage of Docker for users not familiar with it. For more advanced users, the cmdlet can export a usable docker-compose configuration file.

The current version of Wayk Den requires support for Linux containers and bind mounts. Windows containers will be supported in the future.

On Windows, the recommended option is to use https://hub.docker.com/editions/community/docker-ce-desktop-windows[Docker Desktop for Windows]. This version of Docker requires Hyper-V for Linux container support.

For bind mount support with Linux containers on Windows, you need to go in the Docker settings and https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c[select the required drives from the "Shared Drives" section].

On macOS and Linux, follow the instructions here to install Docker CE correctly. It is recommended to use the official Docker packages instead as documented in the https://docs.docker.com/install/[Docker install page].

On Linux, do not forget to https://docs.docker.com/install/linux/linux-postinstall/[add your user to the docker group] after installation.

To confirm that Docker is up and running, use the `docker run hello-world` command. If you don't see the "Hello from Docker!" message, something is wrong with your Docker installation.

== Configuration

The first step is to create a Wayk Den configuration file with mandatory parameters using the `New-WaykDenConfig` command.

You need to choose a realm for your Wayk Den, such as "contoso.net". This realm does not need to be a valid DNS domain name, but it will become your Wayk Den realm used in various places, including the peer-to-peer certificates generated by the Wayk Den built-in certificate authority.

The second mandatory parameter is the external URL at which the Wayk Den will be exposed. We recommend using the "den" subdomain under the domain of your choice, such as "den.contoso.net". The protocol prefix (`http://` or `https://`) also needs to be included.

Create a new Wayk Den configuration file, using "contoso.net" as realm and "https://den.contoso.net" as the external url:

[source, sh]
----
PS > New-WaykDenConfig -Realm contoso.net -ExternalUrl https://den.contoso.net
----

=== Certificate configuration

==== Using certificates with Wayk Den

To expose Wayk Den to the external world, you will need a TLS certificate from a trusted certificate authority such as https://letsencrypt.org/[Let's Encrypt]. Wayk Now will validate certificates in the same way as a browser does for a website.

If you wish to make your own certificate authority, the Root CA certificate will need to be installed in each machine's certificate trust store. If the system browser can validate it, Wayk Now should be able to validate it as well, it's just a lot more work.

Before going any further, check the following points:

1. The certificate name matches your configured external URL. This means that if your external URL is "https://den.contoso.com" then your certificate name should be "den.contoso.com" or "*.contoso.com" if you have a wildcard certificate.

2. The certificate is either in pem + key or pfx (PKCS#12) format. The private key password is only supported for the pfx format.

3. The certificate file contains the certificate *chain* excluding the Root CA. This means that in most cases, you should have a leaf certificate, followed by one or more intermediate certificates. If validation works in a browser but not in Wayk Now, the intermediate certificate is likely missing.

[[certificate-command]]The PEM format is the simplest to work with, since it is the Base64 representation of the DER-encoded certificate in between "-----BEGIN CERTIFICATE-----" and "-----END CERTIFICATE-----" tags. To add the intermediate certificate to the certificate file, just append it after your leaf certificate in a text editor.

[source, sh]
----
PS > Set-WaykDenWebCertificate -CertificatePath /path/to/certificate.pem -PrivateKeyPath /path/to/private_key.key
----

[source, sh]
----
PS > Set-WaykDenWebCertificate -CertificatePath /path/to/certificate.pfx -KeyPassword <password>
----

==== SmallStep third-party can help you

Step and Step-ca are command line tools to ease the process of authority and certificate creation and management. By using your own authority you will be able to use Wayk Den in https without the requirement of paying for a third party certificate. In other hand, managing his own certificate need more configuration for your infrastructure. 

There, we will create an authority and a certificate more in a demonstration purpose, but, with the appropriate knowledge, you can extend that to a production environment.

===== Step/Step-Ca Installation

Unfortunately, Step can't be used on Windows but you can use it through a Linux system under WSL (Windows Subsystem for Linux).

You can install Step on macOS simply by executing `brew install step`

For Linux you need to install https://github.com/smallstep/cli/releases[Step] and https://github.com/smallstep/certificates/releases[Step-ca] from release.

For other Linux distribution (non Debian based) you can build from https://github.com/smallstep/cli[Step] and https://github.com/smallstep/certificates[Step-ca] sources

===== Generate authority and sign certificate

Simply run command `step ca init` and enter asked information. For demo purpose you don't need complex information you can use whatever name you want as PKI and Provisioner. For DNS you can use localhost and for Address you can use something like :8443. This information are used to identify your authority and to know on which address your authority will listen to.

Then run the authority server with `step-ca $HOME/.step/config/ca.json`. In a standard installation, the folder where your CA is generated is  $HOME/.step/

Whith your server running, start a new terminal and type `step ca certificate "DNS" "DNS.pem" "DNS.key"` where DNS is the External Url you provided to your Wayk Den. After that you will find both, the pem and the key, in the folder where you typed the command. Use both of them with the <<certificate-command, command provided before>>.

===== Make your certificate works

To make your certificate valid in browsers you need to import the root_ca  authority to them. You can do it manually by importing the root_ca generated generally under `$HOME/.step/certs`. 

In Windows you can easily import your root_ca in the system store by just double-clicking it. In this case browsers will use it to check the validity of your certificate.

This is true for almost all browsers but Firefox. Firefox use his own keystore so you need to import your root_ca manually. In Firefox type `about:preferences#privacy` in your url, then under `Security` click on `View Certificates...` button and in `Authorities` tab click on `Import`.

On macOS you can avoid all previous manual operation by typing `step certificate install $HOME/.step/certs/root_ca.crt`. 

On Linux you need to do manual operations for all browsers. The system store is not used.

Advanced users can do some script to ease the process of installing root_ca on there infrastructure or they can also use policies to install the root_ca on there domains. You can find more informations about this to this https://support.mozilla.org/en-US/kb/setting-certificate-authorities-firefox[link], this http://www.chromium.org/Home/chromium-security/root-ca-policy[link] and this https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Tools[link]

== Running

Start Wayk Den, and wait for all microservices to start:

[source, sh]
----
PS > Start-WaykDen
----

Once started, Wayk Den listens on http://localhost:4000 by default. We recommend using a reverse tunnel such as https://ngrok.com/[ngrok] or https://www.cloudflare.com/en-ca/products/argo-tunnel/[argo tunnels] from Cloudflare. In this case, a tunnel is used to expose localhost:4000 on the den.contoso.net external url.

You can check that all containers are up and running with the `docker ps -f network=den-network` command.

To confirm everything is correctly configured, you should be able to get a response from the Wayk Den well known configuration endpoint:

[source, sh]
----
curl http://localhost:4000/.well-known/configuration
{"den_router_uri":"https://den.contoso.net/cow","lucid_uri":"https://den.contoso.net/lucid","realm":"contoso.net","wayk_client_id":"zqdvSbCRWdDrj1fQXwzPQbCg"}
----

If you have correctly configured external access, you should be able to get the same response using the external configuration URL (https://den.contoso.net/.well-known/configuration).

Stop Wayk Den, and wait for all microservices to stop:

[source, sh]
----
PS > Stop-WaykDen
----

=== User Management

User using Wayk Now client can log in to be authenticated with Wayk Den Server. The server, by default, will provide a Wayk Den ID to any user who wants to connect to it. The server can be configured in a way forcing the user to be authenticated to accept a connection with the server. The command `Set-WaykDenConfig -LoginRequired True` can be used to force users to log in.

To authenticate user, Wayk Den can be configured to use a specific user group through LDAP integration. Two options are supported: Active Directory and JumpCloud. 

In order to fetch user and group information, a user with read-only LDAP access must first be created.

==== Active Directory

To integrate Active Directory, here are the information needed:

* LDAP server url: ldap://_server_ip_ 
* LDAP user credentials: username and password
* LDAP user group (optional)

It is important to specify the server IP since there is not DNS resolution in the docker container. The user used should be a user with only read-only access. A section below explains how to create a such user. Finally, the user group is not mandatory. If it is not specified, all users will be accepted. If it is specified, only users from that group will be able to be authenticated.

The following command will set LDAP property value for active directory. 

[source, sh]
----
Set-WaykDenConfig -LDAPServerType ActiveDirectory -LDAPUsername ldap-user@contoso.local -LDAPPassword ldap-password -LDAPServerUrl ldap://ldap-server -LDAPUserGroup 'Domain Users'
---- 

===== User creation with read-only access

By default, a new user created in active directory has read-only access on the LDAP server. But that user is also member of the group Domain Users by default. Being member of that group is enough to be able to use that user and log on any domain's computer. To avoid that, we suggest to use a user who is not a member of Domain Users group and has only read-only access on the LDAP server. To do that, a few steps is needed.

First, a new group has to be created, let's say "Read-only Users". Then a new user can be created and added only to that group. After that, the new group can be set as primary group for the user. And finally, the user can be removed from the Domain Users group. This user should be used to configured WaykDen Server.

==== JumpCloud

https://jumpcloud.com/[JumpCloud] is a cloud service who help you to centralize user management. You can create users and groups then use the service call "LDAP-as-a-Service" to access those users and groups from WaykDen. You can read more on https://support.jumpcloud.com/customer/en/portal/articles/2439911-using-jumpcloud-s-ldap-as-a-service[how to use JumpCloud's LDAP-as-a-Service]. 

To integrate Jump Cloud with Wayk Den, here are the information needed :

* LDAP server url : ldaps://ldap.jumpcloud.com:636
* LDAP user credential: username and password
* LDAP Base DN: Distinguised Name where to retrieve users and groups
* LDAP user group (optional)

The LDAP server url should be set to ldaps://ldap.jumpcloud.com:636. JumpCloud provide a non secure access as well, but we don't recommand it. A user who can read the ldap directory should be created following steps https://support.jumpcloud.com/customer/en/portal/articles/2439911-using-jumpcloud-s-ldap-as-a-service#createuser[here]. The username has to be provided with the Distinguished Name (DN), something like `uid=_LDAP_BINDING_USER_,ou=Users,o=_YOUR_ORG_ID_,dc=jumpcloud,dc=com`. The base DN is similar and should be set to `ou=Users,o=_YOUR_ORG_ID_,dc=jumpcloud,dc=com`. Finally, a user group name can be specified to limit user to that group.

The following command will set LDAP property value for JumpCloud.

[source, sh]
----
Set-WaykDenConfig -LDAPServerType JumpCloud -LDAPUsername "uid=ldap-user,ou=Users,o=YOUR_ORG_ID,dc=jumpcloud,dc=com" -LDAPPassword ldap-password -LDAPServerUrl ldaps://ldap.jumpcloud.com:636 -LDAPBaseDn "ou=Users,o=YOUR_ORG_ID,dc=jumpcloud,dc=com -LDAPUserGroup wayk-users"
----

== Usage

Many commands are available to manage the WaykDen server. All those commands required the WaykDen Url and the WaykDen Api Key or the Access Token since you can run them from any path on your system. So you can specify parameters `ServerUrl` and `ApiKey` on every command or you can use the command `Connect-WaykDenUser` to specify these values only once. Information will be kept in environment variables to be used for all future calls. 

[source, sh]
----
PS > Connect-WaykDenUser -DenUrl https://den.ngrok.io -ApiKey 6ezyCcnsZIG6Fa7JpmZDdDLKUEG9yoDM
----

Instant of API Key, you can connect with a user account, and it's token will be used for the commands, but the user need the administrator privileges.

[source, sh]
----
PS > Connect-WaykDenUser -DenUrl https://den.ngrok.io 
----

Once it is done, you should have two environment variables defined.

[source, sh]
----
PS > echo $env:DEN_SERVER_URL
https://den.ngrok.io
PS > echo $env:DEN_API_KEY
6ezyCcnsZIG6Fa7JpmZDdDLKUEG9yoDM
OR
PS > echo $env:DEN_ACCESS_TOKEN
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
----

The command `Disconnect-WaykDenUser` will logout your user on WaykDen, and clear the environment variable of WaykDen.

[source,sh]
----
PS ~/WaykNow-ps> Disconnect-WaykDenUser

----

== Devolutions Jet

Devolutions Jet is a relay server for peer-to-peer connections. By default, jet.wayk.net:8080 is used by Wayk Den. But it is possible to use your own relay server and this section explains how. 

The Devolutions Jet service is not deployed with other Wayk Den services because it makes more sense for that service to be directly exposed in the cloud to get better performance.

That service is also available in a docker container. To launch that service, here is a docker command template that has to be used. 

[source, sh, subs="quotes"]
----
docker run -d --name devolutions-jet -e RUST_LOG=_log_level_ -e JET_INSTANCE=_jet_instance_ -p _port_:8080 devolutions/devolutions-jet: _jet_version_
----

In that command, a few parameters have to be set

- _log_level_: It can be 'error', 'info' or 'debug'. We recommand to set it to 'info'. By default, if RUST_LOG is not specified, the log level will be 'error'.

- _jet_version_: The jet version has to be changed to the specific version that you want to use. All versions are available on https://cloud.docker.com/u/devolutions/repository/docker/devolutions/devolutions-jet[Docker Hub]. 

- _port_: The port uses can also be changed to the port that you prefer. Instead of `8080:8080`, you can change the parameter to `12345:8080` and the exposed port will be 12345. The second port 8080 is only the port number used inside the docker container and it has to be 8080.

- _jet_instance_: The JET_INSTANCE environment variable is used to specified the external URL for that specific Jet server. This address will be used by the WaykNow client to reach the relay server. If you have only one Jet server, the Devolutions Jet Server Url specified in the Wayk Den configuration will be the same as the jet instance value. However, if you want to deploy many jet servers, you can deployed a DNS load balancer who will forward requests to one of the jet server. In a such case, each jet server will specify their external address. It is needed because both peers in a connection has to reach the same jet server. So the WaykNow server will reach one server of the pool and send the jet instance information to the WaykNow client and the client will be able to reach the same Jet server.

Here is a command example to launch Devolutions Jet service

[source, sh]
----
docker run -d --name devolutions jet -e RUST_LOG=info -e JET_INSTANCE=jet.wayk.net -p 8080:8080 devolutions/devolutions-jet: 1.0.0-buster
----

To be sure that your Devolutions Jet server is running, you can run the command `docker logs devolutions-jet` where you should be able to see that your server is listening on the right port

[source, sh]
----
INFO 2019-08-07T15:32:20Z: devolutions_jet: Starting http server ...
INFO 2019-08-07T15:32:20Z: devolutions_jet::http::http_server: Loading http middlewares
INFO 2019-08-07T15:32:20Z: devolutions_jet::http::http_server: Loading http controllers
INFO 2019-08-07T15:32:20Z: devolutions_jet::http::http_server: Configuring http router
INFO 2019-08-07T15:32:20Z: saphir::server: Saphir successfully started and listening on http://0.0.0.0:10256/
INFO 2019-08-07T15:32:20Z: devolutions_jet: Http server succesfully started
INFO 2019-08-07T15:32:20Z: devolutions_jet: Starting TCP jet server...
INFO 2019-08-07T15:32:20Z: devolutions_jet: TCP jet server started successfully. Listening on 0.0.0.0:8080
----

Once you have deployed a jet server, you can update the jet server parameter in your Wayk Den configuration with the command `Set-WaykDenConfig -JetServerUrl _jetServerUrl_`. After, your jet server will be used by WaykNow client to establish peer-to-peer connection.
