= Devolutions Jet

Devolutions Jet is a relay server for peer-to-peer connections. By default, jet.wayk.net:8080 is used by Wayk Den. But it is possible to use your own relay server and this section explains how. 

The Devolutions Jet service is not deployed with other Wayk Den services because it makes more sense for that service to be directly exposed in the cloud to get better performance.

That service is also available in a docker container. To launch that service, here is a docker command template that has to be used. 

[source, sh, subs="quotes"]
----
docker run -d --name devolutions-jet -e RUST_LOG=_log_level_ -e JET_INSTANCE=_jet_instance_ -p _port_:8080 devolutions/devolutions-jet: _jet_version_
----

In that command, a few parameters have to be set

- _log_level_: It can be 'error', 'info' or 'debug'. We recommand to set it to 'info'. By default, if RUST_LOG is not specified, the log level will be 'error'.

- _jet_version_: The jet version has to be changed to the specific version that you want to use. All versions are available on https://cloud.docker.com/u/devolutions/repository/docker/devolutions/devolutions-jet[Docker Hub]. 

- _port_: The port uses can also be changed to the port that you prefer. Instead of `8080:8080`, you can change the parameter to `12345:8080` and the exposed port will be 12345. The second port 8080 is only the port number used inside the docker container and it has to be 8080.

- _jet_instance_: The JET_INSTANCE environment variable is used to specified the external URL for that specific Jet server. This address will be used by the WaykNow client to reach the relay server. If you have only one Jet server, the Devolutions Jet Server Url specified in the Wayk Den configuration will be the same as the jet instance value. However, if you want to deploy many jet servers, you can deployed a DNS load balancer who will forward requests to one of the jet server. In a such case, each jet server will specify their external address. It is needed because both peers in a connection has to reach the same jet server. So the WaykNow server will reach one server of the pool and send the jet instance information to the WaykNow client and the client will be able to reach the same Jet server.

Here is a command example to launch Devolutions Jet service

[source, sh]
----
docker run -d --name devolutions jet -e RUST_LOG=info -e JET_INSTANCE=jet.wayk.net -p 8080:8080 devolutions/devolutions-jet: 1.0.0-buster
----

To be sure that your Devolutions Jet server is running, you can run the command `docker logs devolutions-jet` where you should be able to see that your server is listening on the right port

[source, sh]
----
INFO 2019-08-07T15:32:20Z: devolutions_jet: Starting http server ...
INFO 2019-08-07T15:32:20Z: devolutions_jet::http::http_server: Loading http middlewares
INFO 2019-08-07T15:32:20Z: devolutions_jet::http::http_server: Loading http controllers
INFO 2019-08-07T15:32:20Z: devolutions_jet::http::http_server: Configuring http router
INFO 2019-08-07T15:32:20Z: saphir::server: Saphir successfully started and listening on http://0.0.0.0:10256/
INFO 2019-08-07T15:32:20Z: devolutions_jet: Http server succesfully started
INFO 2019-08-07T15:32:20Z: devolutions_jet: Starting TCP jet server...
INFO 2019-08-07T15:32:20Z: devolutions_jet: TCP jet server started successfully. Listening on 0.0.0.0:8080
----

Once you have deployed a jet server, you can update the jet server parameter in your Wayk Den configuration with the command `Set-WaykDenConfig -JetServerUrl _jetServerUrl_`. After, your jet server will be used by WaykNow client to establish peer-to-peer connection.
