= Smallstep Certificate Authority

`step` and `step-ca` are command-line tools to ease the process of authority and certificate creation and management. By using your own authority you will be able to use Wayk Den in https without the requirement of paying for a third party certificate. In other hand, managing his own certificate need more configuration for your infrastructure. 

There, we will create an authority and a certificate more in a demonstration purpose, but, with the appropriate knowledge, you can extend that to a production environment.

== Smallstep Installation

Unfortunately, step can't be used on Windows but you can use it through a Linux system under WSL (Windows Subsystem for Linux).

You can install step on macOS simply by executing `brew install step`

For Linux you need to install https://github.com/smallstep/cli/releases[step] and https://github.com/smallstep/certificates/releases[step-ca] from release.

For other Linux distribution (non Debian based) you can build from https://github.com/smallstep/cli[step] and https://github.com/smallstep/certificates[step-ca] sources

== Creating a new Certificate Authority

Simply run command `step ca init` and enter asked information. For demo purpose you don't need complex information you can use whatever name you want as PKI and Provisioner. For DNS you can use localhost and for Address you can use something like :8443. This information are used to identify your authority and to know on which address your authority will listen to.

Then run the authority server with `step-ca $HOME/.step/config/ca.json`. In a standard installation, the folder where your CA is generated is  $HOME/.step/

== Generating your Server Leaf Certificate

Whith your server running, start a new terminal and type `step ca certificate "DNS" "DNS.pem" "DNS.key"` where DNS is the External Url you provided to your Wayk Den. After that you will find both, the pem and the key, in the folder where you typed the command. Use both of them with the <<certificate-command, command provided before>>.

== Trusting your new Certificate Authority

To make your certificate valid in browsers you need to import the root_ca  authority to them. You can do it manually by importing the root_ca generated generally under `$HOME/.step/certs`. 

In Windows you can easily import your root_ca in the system store by just double-clicking it. In this case browsers will use it to check the validity of your certificate.

This is true for almost all browsers but Firefox. Firefox use his own keystore so you need to import your root_ca manually. In Firefox type `about:preferences#privacy` in your url, then under `Security` click on `View Certificates...` button and in `Authorities` tab click on `Import`.

On macOS you can avoid all previous manual operation by typing `step certificate install $HOME/.step/certs/root_ca.crt`. 

On Linux you need to do manual operations for all browsers. The system store is not used.

Advanced users can do some script to ease the process of installing root_ca on there infrastructure or they can also use policies to install the root_ca on there domains. You can find more informations about this to this https://support.mozilla.org/en-US/kb/setting-certificate-authorities-firefox[link], this http://www.chromium.org/Home/chromium-security/root-ca-policy[link] and this https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Tools[link]
